### ISSUE TITLE
Traceback is shown when command fails in Taskfile

### ISSUE THREAD

**Issue by EmilySeville7cfg** [go-task/task#1084]
> Thanks for your bug report!
>
> Before submitting this issue, please make sure the same problem was
> not already reported by someone else.
>
> Please describe the bug you're facing. Consider pasting example
> Taskfiles showing how to reproduce the problem.

- Task version: 3.22.0
- Operating System: Ubuntu 22.04.1 LTS

# Steps to reproduce

- clone [this](https://github.com/command-line-interface-pages/site.github.io.git) repository
- open **content/future.md** file
- change 13th line to `We think that it's better not to extend Markdown with some brand new              unknown`
- run `task`
- obtain:

```
task: [lint-with-jsonschema-cli] for file in data/*; do
  file=$(sed -E 's|.*/(.+)\.yaml|\1|' <<<"$file")
  env -C "data" jsonschema-cli validate "../schemas/$file.json" "$file.yaml"
done

task: [lint-with-markdownlint] markdownlint **/*.md
content/future.md:13:81 MD013/line-length Line length [Expected: 80; Actual: 89]
Traceback (most recent call last):
  File "/home/emilyseville7cfg/.local/bin/jsonschema-cli", line 5, in <module>
    from jsonschema_cli.cli import run
  File "/home/emilyseville7cfg/.local/lib/python3.10/site-packages/jsonschema_cli/cli.py", line 4, in <module>
    import jsonschema
  File "/home/emilyseville7cfg/.local/lib/python3.10/site-packages/jsonschema/__init__.py", line 11, in <module>
    from jsonschema.exceptions import (
  File "/home/emilyseville7cfg/.local/lib/python3.10/site-packages/jsonschema/exceptions.py", line 11, in <module>
    from jsonschema import _utils
  File "/home/emilyseville7cfg/.local/lib/python3.10/site-packages/jsonschema/_utils.py", line 6, in <module>
    from jsonschema.compat import MutableMapping, str_types, urlsplit
  File "/home/emilyseville7cfg/.local/lib/python3.10/site-packages/jsonschema/compat.py", line 25, in <module>
    from urllib.request import pathname2url, urlopen
  File "/usr/lib/python3.10/urllib/request.py", line 88, in <module>
    import http.client
  File "/usr/lib/python3.10/http/client.py", line 71, in <module>
    import email.parser
  File "/usr/lib/python3.10/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "/usr/lib/python3.10/email/feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "/usr/lib/python3.10/email/_policybase.py", line 9, in <module>
    from email.utils import _has_surrogates
  File "/usr/lib/python3.10/email/utils.py", line 33, in <module>
    from email._parseaddr import quote
  File "/usr/lib/python3.10/email/_parseaddr.py", line 16, in <module>
    import time, calendar
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1012, in get_code
  File "<frozen importlib._bootstrap_external>", line 672, in _compile_bytecode
KeyboardInterrupt
task: Failed to run task "lint-with-markdownlint": exit status 1
```

![image](https://user-images.githubusercontent.com/42812113/227685548-20686e90-1667-48cb-b623-5963fc337c32.png)

[Here](https://github.com/command-line-interface-pages/site.github.io/blob/main/Taskfile.yaml) is my Taskfile. I expected no traceback shown.

**Comment by pd93** [comment]
I'm confused as to where the weird error message is. The output from Task looks fine to me. The stacktrace in your output is coming from `markdownlint`, not Task.

**Comment by EmilySeville7cfg** [comment]
It's weird, but when I execute `markdownlint content/future.md` then I get this:

```
content/future.md:13:81 MD013/line-length Line length [Expected: 80; Actual: 88]
```

When I type `shopt -s globstar; markdownlint **/*.md` I get this:

```
content/future.md:13:81 MD013/line-length Line length [Expected: 80; Actual: 88]
themes/terminal/COMMUNITY-FEATURES.md:4:81 MD013/line-length Line length [Expected: 80; Actual: 104]
themes/terminal/COMMUNITY-FEATURES.md:15:81 MD013/line-length Line length [Expected: 80; Actual: 104]
themes/terminal/COMMUNITY-FEATURES.md:24:81 MD013/line-length Line length [Expected: 80; Actual: 119]
themes/terminal/exampleSite/content/about.md:9:81 MD013/line-length Line length [Expected: 80; Actual: 99]
themes/terminal/exampleSite/content/about.md:11:81 MD013/line-length Line length [Expected: 80; Actual: 173]
themes/terminal/exampleSite/content/about.md:13:81 MD013/line-length Line length [Expected: 80; Actual: 96]
themes/terminal/exampleSite/content/about.md:17:81 MD013/line-length Line length [Expected: 80; Actual: 86]
themes/terminal/exampleSite/content/about.md:18:81 MD013/line-length Line length [Expected: 80; Actual: 96]
themes/terminal/exampleSite/content/posts/hello.md:9:81 MD013/line-length Line length [Expected: 80; Actual: 453]
themes/terminal/exampleSite/content/posts/hello.md:11:81 MD013/line-length Line length [Expected: 80; Actual: 306]
themes/terminal/exampleSite/content/posts/hello.md:13:81 MD013/line-length Line length [Expected: 80; Actual: 335]
themes/terminal/exampleSite/content/posts/hello.md:15:81 MD013/line-length Line length [Expected: 80; Actual: 121]
themes/terminal/exampleSite/content/posts/hello.md:18:81 MD013/line-length Line length [Expected: 80; Actual: 135]
themes/terminal/exampleSite/content/showcase.md:9:81 MD013/line-length Line length [Expected: 80; Actual: 453]
themes/terminal/exampleSite/content/showcase.md:11:81 MD013/line-length Line length [Expected: 80; Actual: 306]
themes/terminal/exampleSite/content/showcase.md:15:81 MD013/line-length Line length [Expected: 80; Actual: 324]
themes/terminal/exampleSite/content/showcase.md:75:81 MD013/line-length Line length [Expected: 80; Actual: 297]
themes/terminal/exampleSite/content/showcase.md:78:81 MD013/line-length Line length [Expected: 80; Actual: 105]
themes/terminal/exampleSite/content/showcase.md:79:81 MD013/line-length Line length [Expected: 80; Actual: 137]
themes/terminal/exampleSite/content/showcase.md:84:81 MD013/line-length Line length [Expected: 80; Actual: 423]
themes/terminal/LICENSE.md:1 MD041/first-line-heading/first-line-h1 First line in a file should be a top-level heading [Context: "The MIT License (MIT)"]
themes/terminal/README.md:5 MD001/heading-increment/header-increment Heading levels should only increment by one level at a time [Expected: h2; Actual: h3]
themes/terminal/README.md:5 MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Below] [Context: "### DEMO - https://hugo-terminal.now.sh/"]
themes/terminal/README.md:6:58 MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: '.']
themes/terminal/README.md:22:3 MD051/link-fragments Link fragments should be valid [Context: "[Licence](#licence)"]
themes/terminal/README.md:26:81 MD013/line-length Line length [Expected: 80; Actual: 97]
themes/terminal/README.md:27:81 MD013/line-length Line length [Expected: 80; Actual: 96]
themes/terminal/README.md:32 MD001/heading-increment/header-increment Heading levels should only increment by one level at a time [Expected: h3; Actual: h4]
themes/terminal/README.md:34:81 MD013/line-length Line length [Expected: 80; Actual: 136]
themes/terminal/README.md:36 MD031/blanks-around-fences Fenced code blocks should be surrounded by blank lines [Context: "```go"]
themes/terminal/README.md:37:81 MD013/line-length Line length [Expected: 80; Actual: 101]
themes/terminal/README.md:38 MD031/blanks-around-fences Fenced code blocks should be surrounded by blank lines [Context: "```"]
themes/terminal/README.md:39:81 MD013/line-length Line length [Expected: 80; Actual: 154]
themes/terminal/README.md:41 MD031/blanks-around-fences Fenced code blocks should be surrounded by blank lines [Context: "```go"]
themes/terminal/README.md:42:81 MD013/line-length Line length [Expected: 80; Actual: 177]
themes/terminal/README.md:43 MD031/blanks-around-fences Fenced code blocks should be surrounded by blank lines [Context: "```"]
themes/terminal/README.md:44:81 MD013/line-length Line length [Expected: 80; Actual: 161]
themes/terminal/README.md:46 MD031/blanks-around-fences Fenced code blocks should be surrounded by blank lines [Context: "```go"]
themes/terminal/README.md:47:81 MD013/line-length Line length [Expected: 80; Actual: 113]
themes/terminal/README.md:72:81 MD013/line-length Line length [Expected: 80; Actual: 96]
themes/terminal/README.md:74 MD040/fenced-code-language Fenced code blocks should have a language specified [Context: "````"]
themes/terminal/README.md:80:81 MD013/line-length Line length [Expected: 80; Actual: 570]
themes/terminal/README.md:84:81 MD013/line-length Line length [Expected: 80; Actual: 206]
themes/terminal/README.md:115:81 MD013/line-length Line length [Expected: 80; Actual: 323]
themes/terminal/README.md:136:81 MD013/line-length Line length [Expected: 80; Actual: 136]
themes/terminal/README.md:147:81 MD013/line-length Line length [Expected: 80; Actual: 155]
themes/terminal/README.md:187:81 MD013/line-length Line length [Expected: 80; Actual: 111]
themes/terminal/README.md:193:81 MD013/line-length Line length [Expected: 80; Actual: 133]
themes/terminal/README.md:251:81 MD013/line-length Line length [Expected: 80; Actual: 94]
themes/terminal/README.md:259:81 MD013/line-length Line length [Expected: 80; Actual: 181]
themes/terminal/README.md:269:81 MD013/line-length Line length [Expected: 80; Actual: 198]
themes/terminal/README.md:270:81 MD013/line-length Line length [Expected: 80; Actual: 173]
themes/terminal/README.md:271:81 MD013/line-length Line length [Expected: 80; Actual: 179]
themes/terminal/README.md:275:81 MD013/line-length Line length [Expected: 80; Actual: 259]
themes/terminal/README.md:277:81 MD013/line-length Line length [Expected: 80; Actual: 192]
themes/terminal/README.md:281:81 MD013/line-length Line length [Expected: 80; Actual: 200]
themes/terminal/README.md:285:81 MD013/line-length Line length [Expected: 80; Actual: 244]
themes/terminal/README.md:287:81 MD013/line-length Line length [Expected: 80; Actual: 126]
themes/terminal/README.md:296:81 MD013/line-length Line length [Expected: 80; Actual: 148]
themes/terminal/README.md:302:81 MD013/line-length Line length [Expected: 80; Actual: 213]
themes/terminal/README.md:304 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
themes/terminal/README.md:309:81 MD013/line-length Line length [Expected: 80; Actual: 185]
themes/terminal/USERS.md:1 MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Below] [Context: "# Meet the users of Terminal theme!"]
themes/terminal/USERS.md:1:35 MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: '!']
themes/terminal/USERS.md:16:81 MD013/line-length Line length [Expected: 80; Actual: 94]
themes/terminal/USERS.md:17:81 MD013/line-length Line length [Expected: 80; Actual: 108]
themes/terminal/USERS.md:35:81 MD013/line-length Line length [Expected: 80; Actual: 91]
themes/terminal/USERS.md:42:81 MD013/line-length Line length [Expected: 80; Actual: 111]
themes/terminal/USERS.md:49:81 MD013/line-length Line length [Expected: 80; Actual: 112]
themes/terminal/USERS.md:53:81 MD013/line-length Line length [Expected: 80; Actual: 97]
```

But when I run `task` it crashes with this error:

```
task: [lint-with-jsonschema-cli] for file in data/*; do
  file=$(sed -E 's|.*/(.+)\.yaml|\1|' <<<"$file")
  env -C "data" jsonschema-cli validate "../schemas/$file.json" "$file.yaml"
done

task: [lint-with-markdownlint] markdownlint **/*.md
content/future.md:13:81 MD013/line-length Line length [Expected: 80; Actual: 88]
Traceback (most recent call last):
  File "/home/emilyseville7cfg/.local/bin/jsonschema-cli", line 5, in <module>
    from jsonschema_cli.cli import run
  File "/home/emilyseville7cfg/.local/lib/python3.10/site-packages/jsonschema_cli/cli.py", line 4, in <module>
    import jsonschema
  File "/home/emilyseville7cfg/.local/lib/python3.10/site-packages/jsonschema/__init__.py", line 11, in <module>
    from jsonschema.exceptions import (
  File "/home/emilyseville7cfg/.local/lib/python3.10/site-packages/jsonschema/exceptions.py", line 11, in <module>
    from jsonschema import _utils
  File "/home/emilyseville7cfg/.local/lib/python3.10/site-packages/jsonschema/_utils.py", line 6, in <module>
    from jsonschema.compat import MutableMapping, str_types, urlsplit
  File "/home/emilyseville7cfg/.local/lib/python3.10/site-packages/jsonschema/compat.py", line 25, in <module>
    from urllib.request import pathname2url, urlopen
  File "/usr/lib/python3.10/urllib/request.py", line 88, in <module>
    import http.client
  File "/usr/lib/python3.10/http/client.py", line 1394, in <module>
    import ssl
  File "/usr/lib/python3.10/ssl.py", line 99, in <module>
    import _ssl             # if we can't import it, let the error propagate
KeyboardInterrupt
task: Failed to run task "lint-with-markdownlint": exit status 1
```

**Comment by richard-hajek** [comment]
KeyboardInterrupt usually means, that you pressed Ctrl+C, can you confirm whether or not is that the case?

**Comment by EmilySeville7cfg** [comment]
I haven't pressed this key combination.

**Comment by richard-hajek** [comment]
Eyo, I just realized, this traceback:

```
ontent/future.md:13:81 MD013/line-length Line length [Expected: 80; Actual: 88]
Traceback (most recent call last):
  File "/home/emilyseville7cfg/.local/bin/jsonschema-cli", line 5, in <module>
    from jsonschema_cli.cli import run
  File "/home/emilyseville7cfg/.local/lib/python3.10/site-packages/jsonschema_cli/cli.py", line 4, in <module>
    import jsonschema
  File "/home/emilyseville7cfg/.local/lib/python3.10/site-packages/jsonschema/__init__.py", line 11, in <module>
    from jsonschema.exceptions import (
  File "/home/emilyseville7cfg/.local/lib/python3.10/site-packages/jsonschema/exceptions.py", line 11, in <module>
    from jsonschema import _utils
```

Is from the `jsonschema-cli` not the markdownlint...

**Comment by pd93** [comment]
Unless I've misunderstood something, this issue is not related to Task, so I'm closing this for now.
