### ISSUE TITLE
Crash on malformed Taskfile.yml

### ISSUE THREAD

**Issue by ldanko** [go-task/task#361]
- Task version: 3.0.0
- Linux
- Example Taskfile showing the issue:
```yaml
version: '3'

tasks:
  some_task:
```

Application crashes when task file is malformed. For bigger task files, error can be hard to spot. It would be nice if task would return with error message pointing what and where was wrong.
```
$ task some_task
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x66fea8]

goroutine 1 [running]:
github.com/go-task/task/v3/internal/taskfile/read.Taskfile(0x0, 0x0, 0x73786c, 0xc, 0x636300000040c086, 0xc0001259a0, 0x5)
	/home/runner/work/task/task/internal/taskfile/read/taskfile.go:122 +0x9e8
github.com/go-task/task/v3.(*Executor).Setup(0xc000140210, 0xc000140210, 0x0)
	/home/runner/work/task/task/task.go:109 +0x89
main.main()
	/home/runner/work/task/task/cmd/task/task.go:142 +0x9fe
```

**Comment by ldanko** [comment]
It seems it duplicates #338

**Comment by andreynering** [comment]
> It seems it duplicates #338

Yep...
