### ISSUE TITLE
vars:sh:read throws

### ISSUE THREAD

**Issue by geek-merlin** [go-task/task#420]
```
merlin@thinker ~/tmp $ uname -a
Linux thinker 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
merlin@thinker ~/tmp $ task --version
Task version: 3.0.0
merlin@thinker ~/tmp $ task
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5a2394]

goroutine 1 [running]:
mvdan.cc/sh/v3/interp.(*Runner).readLine(0xc00019ab40, 0x0, 0x1, 0x0, 0xffffffffffffffff, 0xc000156150, 0x747390)
	/home/runner/go/pkg/mod/mvdan.cc/sh/v3@v3.1.2/interp/builtin.go:676 +0x84
mvdan.cc/sh/v3/interp.(*Runner).builtinCode(0xc00019ab40, 0x7a0600, 0xc0000140b0, 0x1000100000000, 0xc0001d4030, 0x4, 0xc000196910, 0x1, 0x1, 0x0)
	/home/runner/go/pkg/mod/mvdan.cc/sh/v3@v3.1.2/interp/builtin.go:490 +0xb87
mvdan.cc/sh/v3/interp.(*Runner).call(0xc00019ab40, 0x7a0600, 0xc0000140b0, 0x1000100000000, 0xc000196900, 0x2, 0x2)
	/home/runner/go/pkg/mod/mvdan.cc/sh/v3@v3.1.2/interp/runner.go:729 +0x38e
mvdan.cc/sh/v3/interp.(*Runner).cmd(0xc00019ab40, 0x7a0600, 0xc0000140b0, 0x79f100, 0xc0001c5500)
	/home/runner/go/pkg/mod/mvdan.cc/sh/v3@v3.1.2/interp/runner.go:335 +0x1696
mvdan.cc/sh/v3/interp.(*Runner).stmtSync(0xc00019ab40, 0x7a0600, 0xc0000140b0, 0xc0001c7800)
	/home/runner/go/pkg/mod/mvdan.cc/sh/v3@v3.1.2/interp/runner.go:275 +0x312
mvdan.cc/sh/v3/interp.(*Runner).stmt(0xc00019ab40, 0x7a0600, 0xc0000140b0, 0xc0001c7800)
	/home/runner/go/pkg/mod/mvdan.cc/sh/v3@v3.1.2/interp/runner.go:256 +0x1e9
mvdan.cc/sh/v3/interp.(*Runner).cmd(0xc00019ab40, 0x7a0600, 0xc0000140b0, 0x79efc0, 0xc000196840)
	/home/runner/go/pkg/mod/mvdan.cc/sh/v3@v3.1.2/interp/runner.go:347 +0xfcf
mvdan.cc/sh/v3/interp.(*Runner).stmtSync(0xc00019ab40, 0x7a0600, 0xc0000140b0, 0xc0001c78b0)
	/home/runner/go/pkg/mod/mvdan.cc/sh/v3@v3.1.2/interp/runner.go:275 +0x312
mvdan.cc/sh/v3/interp.(*Runner).stmt(0xc00019ab40, 0x7a0600, 0xc0000140b0, 0xc0001c78b0)
	/home/runner/go/pkg/mod/mvdan.cc/sh/v3@v3.1.2/interp/runner.go:256 +0x1e9
mvdan.cc/sh/v3/interp.(*Runner).stmts(0xc00019ab40, 0x7a0600, 0xc0000140b0, 0xc0001e2000, 0x1, 0x4)
	/home/runner/go/pkg/mod/mvdan.cc/sh/v3@v3.1.2/interp/runner.go:586 +0x56
mvdan.cc/sh/v3/interp.(*Runner).Run(0xc00019ab40, 0x7a0600, 0xc0000140b0, 0x79c040, 0xc00018c140, 0x0, 0xc0001922a0)
	/home/runner/go/pkg/mod/mvdan.cc/sh/v3@v3.1.2/interp/api.go:523 +0x2ec
github.com/go-task/task/v3/internal/execext.RunCommand(0x7a0600, 0xc0000140b0, 0xc000157608, 0x18, 0x9bbaa0)
	/home/runner/work/task/task/internal/execext/exec.go:64 +0x2d3
github.com/go-task/task/v3/internal/compiler/v3.(*CompilerV3).HandleDynamicVar(0xc00005f350, 0x0, 0x0, 0x0, 0x0, 0xc0001d8020, 0x18, 0x0, 0x0, 0x0, ...)
	/home/runner/work/task/task/internal/compiler/v3/compiler_v3.go:86 +0x248
github.com/go-task/task/v3/internal/compiler/v3.(*CompilerV3).GetVariables.func1(0xc000014b08, 0x5, 0x0, 0x0, 0x0, 0x0, 0xc0001d8020, 0x18, 0x0, 0x35)
	/home/runner/work/task/task/internal/compiler/v3/compiler_v3.go:43 +0x16b
github.com/go-task/task/v3/internal/taskfile.(*Vars).Range(0xc00000c680, 0xc000157878, 0x0, 0x0)
	/home/runner/work/task/task/internal/taskfile/var.go:77 +0x114
github.com/go-task/task/v3/internal/compiler/v3.(*CompilerV3).GetVariables(0xc00005f350, 0xc000112ea0, 0x735f5a, 0x7, 0x0, 0x6500737801, 0x400, 0x400)
	/home/runner/work/task/task/internal/compiler/v3/compiler_v3.go:57 +0x158
github.com/go-task/task/v3.(*Executor).CompiledTask(0xc000116210, 0x735f5a, 0x7, 0x0, 0x70cbe0, 0xc000080000, 0x7f2411a99e98)
	/home/runner/work/task/task/variables.go:21 +0xd1
github.com/go-task/task/v3.(*Executor).RunTask(0xc000116210, 0x7a05c0, 0xc00018c040, 0x735f5a, 0x7, 0x0, 0x69eb7f, 0x10)
	/home/runner/work/task/task/task.go:250 +0x67
github.com/go-task/task/v3.(*Executor).Run(0xc000116210, 0x7a05c0, 0xc00018c000, 0xc00000c720, 0x1, 0x1, 0x0, 0xe)
	/home/runner/work/task/task/task.go:94 +0x3aa
main.main()
	/home/runner/work/task/task/cmd/task/task.go:179 +0xc6c

```

**Comment by andreynering** [comment]
Hi @geek-merlin,

Can you please attach a Taskfile that reproduces the issue?

The stacktrace says this is being throw by the mvdan/sh lib, so knowing which shell command is being ran would be really helpful.

**Comment by geek-merlin** [comment]
(In fact i was looking for a workaround for #421.)
And this is the file:

```
version: '3'
tasks:
  default:
    cmds:
      - 'echo Input: $input'
      - 'echo Input: {{.input}}'
    vars:
      input:
      # Throws.
        sh: 'read input && echo input'

```

**Comment by andreynering** [comment]
I just opened a fix for the panic upstream at https://github.com/mvdan/sh/pull/654.

You'll just get a nicer error, though. I'm not sure if we should support reading variables from the input like that. Is there any reason why you don't just pass variable via ENV or CLI?

**Comment by geek-merlin** [comment]
> Is there any reason why you don't just pass variable via ENV or CLI?

I'm providing commands with parameters and asking missing parameters is much better UX.
